name: PR CI

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_VERSION: 1.14.7

jobs:
  #################################################
  # Detect Changed Packages
  #################################################
  detect:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set.outputs.packages }}
    steps:
      - uses: actions/checkout@v5

      - id: set
        run: |
          CHANGED=$(git diff --name-only origin/main HEAD | grep packages || true)
          PKGS=$(echo "$CHANGED" | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "packages=$PKGS" >> $GITHUB_OUTPUT
          echo "Detected packages: $PKGS"

  #################################################
  # Build + Test + Terraform Plan
  #################################################
  build-test-plan:
    needs: detect
    runs-on: ubuntu-latest
    if: ${{ needs.detect.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect.outputs.packages) }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install / Build / Test
        run: |
          PKG=packages/${{ matrix.package }}
          if [ -f "$PKG/package.json" ]; then
            npm ci --prefix $PKG
            npm run build --prefix $PKG || true

            if ls $PKG/test/*.ts 1> /dev/null 2>&1; then
              npm run test --prefix $PKG
            else
              echo "No tests found"
            fi
          fi

      - name: Terraform Plan (if exists)
        run: |
          PKG_DIR=packages/${{ matrix.package }}/infra
          if [ -d "$PKG_DIR" ]; then
            terraform -chdir="$PKG_DIR" init
            terraform -chdir="$PKG_DIR" plan
          fi

  #################################################
  # Deploy to Dev
  #################################################
  deploy-dev:
    needs: build-test-plan
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: dev
      runner-name: ubuntu-latest
    secrets: inherit