name: Release Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-versioning:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/create-github-app-token@v2
        id: token
        with:
          api-id: ${{ secrets.GITHUB_APP_ID }}
          private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.token.outputs.token }}
          monorepo-tags: true

  deploy-dev:
    needs: release-versioning
    if: ${{ needs.release-versioning.outputs.released == 'true' }}
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: dev
      runner-name: ubuntu-latest
    secrets: inherit

  deploy-test:
    needs: deploy-dev
    if: ${{ needs.deploy-dev.result == 'success' }}
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: test
      runner-name: ubuntu-latest
    secrets: inherit

  deploy-preprod:
    needs: deploy-test
    if: ${{ needs.deploy-test.result == 'success' }}
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: pre-prod
      runner-name: ubuntu-latest
    secrets: inherit

  deploy-prod:
    needs: deploy-preprod
    if: ${{ needs.deploy-preprod.result == 'success' }}
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: prod
      runner-name: ubuntu-latest
    secrets: inherit